version: "3.9"

services:
  mysql:
    image: mysql/mysql-server:8.0.32
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: mediscreen_db_patient
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    expose:
      - "3306"
    networks:
        - web-server
    restart: unless-stopped

  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: Projet9Note
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGODB_PORT: 27017
    networks:
      - web-server



  patient:
    image : patientpatient2
    build :
      context: ./Projet9
      dockerfile: Dockerfile
    container_name: projet9_patient
    environment:
      SERVER_PORT: 8089
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: mediscreen_db_patient
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      #SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mediscreen_db_patient?autoReconnect=true&useSSL=false&serverTimezone=UTC
      #SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    networks:
        - web-server
    ports:
      - "8089:8089"
    depends_on:
      - mysql
    restart: unless-stopped




  note:
    image: notenote
    build:
      context: ./Note
      dockerfile: Dockerfile
    container_name: projet9_note
    networks:
    - web-server
    ports:
      - "8091:8091"
    depends_on:
      - mongo
    restart: unless-stopped

  patientanlysis:
    image: analyseanalyse
    build:
      context: ./PatientAnalysis
      dockerfile: Dockerfile
    container_name: patient_analysis
    networks:
      - web-server
    ports:
      - "8092:8092"
    depends_on:
      - patient
      - note
    restart: unless-stopped

  front:
    container_name: front
    image: p9gfrontv4
    build:
      context: ./p9front
      dockerfile: Dockerfile
    networks:
      - web-server
    ports:
      - "3000:80"
    depends_on:
      - patient
      - note
      - patientanlysis
    restart: unless-stopped

networks:
  web-server:
    driver: bridge
