version: '3'

services:
  mysql:
    image: mysql/mysql-server:8.0.32
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: mediscreen_db_patient
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    expose:
      - "3307"
    networks:
      - web-server
    restart: always

  patient:
    image : p9patient
    container_name: projet9_patient
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mediscreen_db_patient?autoReconnect=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    networks:
      - web-server
    ports:
      - "8089:8089"
    expose:
      - "8089"
    depends_on:
      - mysql
    restart: always

  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - web-server

  note:
    image: note
    container_name: projet9_note
    networks:
      - web-server
    ports:
      - "8091:8091"
    depends_on:
      - mongo

  patientanlysis:
    image: patientanalysis
    container_name: patient_analysis
    networks:
      - web-server
    ports:
      - "8092:8092"
    depends_on:
      - patient
      - note


networks:
  web-server:
    driver: bridge
